quadrantChart
    title Security and Usability of Bitcoin Wallets
    x-axis Low Security --> High Security
    y-axis Low Usability --> High Usability
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Bitcoin Core": [0.9, 0.4]
    "Electrum": [0.7, 0.7]
    "Armory": [0.95, 0.3]
    "Bitcoin Wallet": [0.6, 0.8]
    "Mycelium": [0.7, 0.8]
    "Coinbase": [0.8, 0.9]
    "BitPay": [0.6, 0.7]
    "Our Target Product": [0.9, 0.7]
